/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    media: Media;
    shoots: Shoot;
    users: User;
    people: Person;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Shoot {
  id: number;
  shootName: string;
  year: string;
  Tag: string;
  Photographer: Person;
  Stylist: Person;
  ArtDirector: Person;
  MakeUp?: (number | null) | Person;
  Hair?: (number | null) | Person;
  Model?: (number | null) | Person;
  media:  Media;
  mainPicture:  Media;
  smallTop:  Media;
  middleSplit:  Media;
  SplitWord: string;
  row1:  Media;
  row2:  Media;
  row3:  Media;
  updatedAt: string;
  createdAt: string;
}
export interface Person {
  id: number;
  FirstName: string;
  LastName: string;
  Role: string[];
  Instagram?: string | null;
  photo?: Media | null;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
  | {
    [k: string]: unknown;
  }
  | unknown[]
  | string
  | number
  | boolean
  | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config { }
}